### ISSUE TITLE
Can we Ping a store?

### ISSUE THREAD

**Issue by ainsleyclark** [eko/gocache#105]
Thanks for the great package. I just started using it and it'a exactly what I needed.

Is there an easy/idiomatic way to ping a particular cache store to ensure credentials and addresses are valid?

Many thanks.

**Comment by eko** [comment]
Hi @ainsleyclark,

You have full access to the store objects (redis for instance), so you can use the already available ping command they provides.

I'm not sure I've provided you a good answer so please be free to elaborate more on your question if you need some other answers.

**Comment by ainsleyclark** [comment]
Hey thanks for your reply.

I figured out that we could the store, but a global Ping method on the StoreInterface I think would be really useful.
For go-cache it could just return nil and so fourth.

Many thanks.
