### ISSUE TITLE
How to use different versions of gocahce？

### ISSUE THREAD

**Issue by daniuEvan** [eko/gocache#127]
Hello author:
	Thank you very much for open sourcing the gocache project, it will be very helpful to me; however I don't know much about gochache, I have encountered various problems in using gochache, I can't even run my project, can you make a tutorial on gochache, starting from the main function;
my  errors：
v1：
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/49090129/155871593-f7e925fc-64b7-49b0-863d-8cd147aba069.png">
v2：
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/49090129/155871608-7949d631-3fcf-4385-9cc1-d56951c4b7cc.png">

**Comment by eko** [comment]
Hi,

Code samples lives in the README file.

You issue is that `v2.0.0` release brings `context` as a first argument of all methods (as specified in the release notes here: https://github.com/eko/gocache/releases/tag/v2.0.0).

If you want to add an example directory in the root of the project, you will be really welcome :-)

Closing this issue for now as there is no real issue with the library.
