### ISSUE TITLE
go mod unable to get latest version v2.2.0

### ISSUE THREAD

**Issue by herozzm** [eko/gocache#131]
`go mod tidy`

go: finding module for package github.com/eko/gocache
github.com/eko/gocache: module github.com/eko/gocache@latest found (v1.2.0), but does not contain package github.com/eko/gocache

```go
import (
	"github.com/eko/gocache"
)

func main() {
   //some code
}

**Comment by coolblknerd** [comment]
I'm running into the same issue trying to set-up a Redis store.

**Comment by amarjeet-rai-cko** [comment]
Run `go get -u github.com/eko/gocache/v2`

**Comment by sonu27** [comment]
Try running `go get -u github.com/eko/gocache/v2`

**Comment by razorness** [comment]
You also have to import `github.com/eko/gocache/v2`.

**Comment by eko** [comment]
Closing this issue, thanks all for your answers.
