### ISSUE TITLE
It's impossible to create my own cache

### ISSUE THREAD

**Issue by wexder** [eko/gocache#159]
The `options` struct is not public, so it's not really viable to implement my own cache since I can't use the v3 `Option` type. `Option` is just a func that takes private struct as input so I can't use it in my own package. I think the `options` struct should be public.

**Comment by wexder** [comment]
I very well might be missing something, so please let me know if I'm wrong.

**Comment by eko** [comment]
Hi @wexder,

You're totally right, I've just make the options available publicly: https://github.com/eko/gocache/pull/160

You can now implement your own cache store.

Thank you for reporting this issue!

**Comment by kabelsea** [comment]
Sorry, but this fix didn't solve the problem... all properties in the struct are private!
