### ISSUE TITLE
Suggestion for an easier interface

### ISSUE THREAD

**Issue by mikestefanello** [eko/gocache#167]
I wrote and maintain [pagoda](https://github.com/mikestefanello/pagoda), a rapid, full-stack web development starter kit. I included _gocache_ to provide a flexible way to handle caching that wouldn't have to be changed if you opt for a different cache provider. While I think this module is great, I found the interface to be somewhat cumbersome to deal with so I wrote a wrapper on top of it that I think turned out pretty well. Since this is something I'd like available in other projects, I thought I'd see if it's something you'd be interested in bringing in.

[Here](https://github.com/mikestefanello/pagoda#cache) is the overall explanation of how it works and what is available. And [here](https://github.com/mikestefanello/pagoda/blob/main/services/cache.go) is the client code that provides that.

For quick reference, here is an example:

```go
err := cache.
    Set().
    Key("my-key").
    Tags("tag1", "tag2").
    Expiration(time.Hour * 2).
    Data(myData).
    Save(ctx)
```

**Comment by eko** [comment]
Hello @mikestefanello,

Thank you for your feedback, I like your approach but I think it would be strange to implement a second way of dealing with objects into gocache.

I prefer to let developers implement their own wrapper as you made if you want another way of chaining methods.

Closing this issue for now but feel free to open if you have any issue with existing interface.
