### ISSUE TITLE
Cannot implement StoreInterface's Invalidate method

### ISSUE THREAD

**Issue by sgtsquiggs** [eko/gocache#175]
Cannot figure out how we're supposed to implement `Invalidate` since the invalidation options are private. Cannot retrieve the tags that would be passed to the function.

**Comment by sgtsquiggs** [comment]
I made some sloppy changes on my fork to expose it. I really don't like it but I needed it in a pinch.

https://github.com/eko/gocache/compare/master...sgtsquiggs:gocache:expose-invalidation-options

**Comment by denis111** [comment]
the same happens with Set(ctx context.Context, key any, object T, options ...store.Option) because I can't access Option members like expiration...

**Comment by sgtsquiggs** [comment]
I'll submit a PR and we can get API feedback there.

**Comment by eko** [comment]
Hi, thanks to all the people working on this subject.

As options are now publicly available, this should be fixed.

I close this issue for now but feel free to reopen if you still have any issue.
