### ISSUE TITLE
store.Options does not expose its props, making StoreInterface challenging to implement

### ISSUE THREAD

**Issue by RoxKilly** [eko/gocache#191]
# **Steps for Reproduction**

The docs suggest that the dev can use a custom store by implementing the [StoreInterface][2]. I'm working on a custom cache to use as part of the library's chain cache but one sticking point is the `Set`.  Here is its definition:

```
Set(ctx context.Context, key any, value any, options ...Option) error
```

`Option` is a function that takes and configures an `Options` object, both from the library package.  here is how the library passes it to my cache's setter: [github][3]

Within the library's cache implementations, the configured `Options` object is then read to discern, for example, the expiration date of the cache entry: [example][4]

The issue I face is that Options ([declared here][5]) makes all its properties private, so when I implement my own `Set()`, I have no way to read it to figure out when the cached entry should expire.

How is my custom StoreInterface implementation supposed to figure out the caching options used?

  [1]: https://github.com/eko/gocache
  [2]: https://github.com/eko/gocache#write-your-own-custom-store
  [3]: https://github.com/eko/gocache/blob/v3.1.1/cache/chain.go#L78
  [4]: https://github.com/eko/gocache/blob/v3.1.1/store/go_cache.go#L71
  [5]: https://github.com/eko/gocache/blob/v3.1.1/store/options.go#L10

# Expected behavior:
Custom struct implementing `StoreInterface` can be used in the chain cache

# **Actual behavior**:
Unable to implement interface correctly because the `Options` object passed to my implementation does not expose the options in public properties

# **Platforms**:
All

# **Versions**:
`v3.1.1`

**Comment by RoxKilly** [comment]
I cloned to open a PR and noticed that this has been [fixed in the master branch](https://github.com/eko/gocache/pull/181).  However it hasn't been released yet ([v3.1.2 has the same issue](https://github.com/eko/gocache/blob/v3.1.2/store/options.go#L10)).  Is there a plan to release this change?

**Comment by RoxKilly** [comment]
Feel free to close the issue unless you have something to add.  If upgrading to `v4` is what I'll do.

**Comment by eko** [comment]
Hi @RoxKilly,

Sorry about the delay but yes, the actual fix has been done into the v4 release.

If you really need it, I can add the fix in v3 and make a new patch release.

I close this issue for now but feel free to reopen and tag me if you need it.
