### ISSUE TITLE
cache type error with using generics

### ISSUE THREAD

**Issue by mpasokolov** [eko/gocache#193]
Hello everyone! Can you help me, i don't understand.

4.1.2 version.

my import:

```
	"github.com/eko/gocache/lib/v4/cache"
	"github.com/eko/gocache/lib/v4/store"
	redis_store "github.com/eko/gocache/store/redis/v4"
```

I have this code:

<img width="1362" alt="Снимок экрана 2023-01-18 в 07 48 27" src="https://user-images.githubusercontent.com/39544825/213086733-8b7c5326-0f22-47ee-9619-ccaf34f0ae5e.png">

How to fix it?

**Comment by jrynd** [comment]
You have to replace `T` with the type of the thing that you're trying to store in the cache, i.e. `string`

**Comment by eko** [comment]
Exactly, `T` have to be replaced with your type.

Thank you for your answer.

Closing this issue for now but feel free to reopen if you still have any issue with the library.
