### ISSUE TITLE
Update to module path needed

### ISSUE THREAD

**Issue by otyang** [eko/gocache#209]
I get this error

```go: github.com/otyang/pkg/datastore imports
        github.com/rueidis/rueidis: github.com/rueidis/rueidis@v1.0.3: parsing go.mod:
        module declares its path as: github.com/redis/rueidis
                but was required as: github.com/rueidis/rueidis
```

The go replace directive doesnt work, as the signatures of some functions were changed.

**Comment by eko** [comment]
Hi,

Closing this issue as I think this is now fixed.

There is no more reference to `rueidis/rueidis` in the code:

```bash
$ grep -ri 'github.com/rueidis/rueidis' .
```

(returns nothing)

Please feel free to reopen if you still have any issue!
