### ISSUE TITLE
Store installation fails

### ISSUE THREAD

**Issue by peteraba** [eko/gocache#211]
I'm trying to install gocache for the first time. That in itself seemed fine, but installing stores seems to be broken.

**Steps for Reproduction**

Follow the instructions written in the README for installing gocache
1. with [Bigcache](https://github.com/eko/gocache#memory-using-bigcache)
2. or with [Ristretto](https://github.com/eko/gocache#memory-using-ristretto) store.

**Expected behavior**:

Bigcache or Ristretto stores installed.

**Actual behavior**:

Failure to install stores (2 out of 2)

```
$ go get github.com/eko/gocache/store/bigcache/v4
go: downloading github.com/eko/gocache/store/bigcache/v4 v4.1.2
go: github.com/eko/gocache/lib/v4@v4.1.1: reading github.com/eko/gocache/lib/go.mod at revision lib/v4.1.1: unknown revision lib/v4.1.1 
```

```
go get github.com/eko/gocache/store/ristretto/v4
go: downloading github.com/eko/gocache/store/ristretto/v4 v4.1.2
go: github.com/eko/gocache/lib/v4@v4.1.1: reading github.com/eko/gocache/lib/go.mod at revision lib/v4.1.1: unknown revision lib/v4.1.1
```

**Platforms**:

OS: Linux (Fedora 38)
Go: go1.20.4 linux/amd64 

**Versions**:

Which versions are you running? v4.1.3

**Comment by n4dwxihyeyhes2** [comment]
The same with `go_cache` v4.1.2 - it refers to not existing `github.com/eko/gocache/lib/v4 v4.1.1` - see https://github.com/eko/gocache/blob/store/go_cache/v4.1.2/store/go_cache/go.mod

**Comment by Ashtonian** [comment]
https://github.com/eko/gocache/issues/214. Redis cluster is also impacted.


@eko Sorry to tag, can you do a quick release as the gocache lib is currently broken for 3 of the stores on master.

**Comment by eko** [comment]
Hi @Ashtonian,

Thank you, I am currently off and have no laptop but I write on top of my todo list to make a new release on monday.

**Comment by eko** [comment]
Hi @peteraba @Ashtonian,

All stores should now be updated and tagged to use lib `v4.1.3` (latest one).

If you still have any issue with Go module cache, please for the version with the latest store version, for instance:

```bash
$ go get github.com/eko/gocache/store/ristretto/v4@v4.2.0

go: downloading github.com/eko/gocache/store/ristretto/v4 v4.2.0
go: added github.com/eko/gocache/lib/v4 v4.1.3
go: added github.com/eko/gocache/store/ristretto/v4 v4.2.0
go: added github.com/golang/mock v1.6.0
go: added golang.org/x/exp v0.0.0-20230315142452-642cacee5cc0
```

Sorry about that and thank you for your patience!

**Comment by eko** [comment]
Closing this issue for now but feel free to reopen if you still have any issue!

**Comment by Ashtonian** [comment]
works, thank you!
