### ISSUE TITLE
Cache race condition problem

### ISSUE THREAD

**Issue by Kachit** [eko/gocache#233]
Hello. I am using your library and I have a problem with concurrency. Two parallel requests to empty cache not found data and fetching it from database twice. I think RWMutex will solve this problem, but maybe I need to use map of RWMutexes by cache keys for example:
```go
cacheMap := map[string]sync.RWMutex{"my-key":sync.RWMutex{}}
```
Do you have ideas how to solve this problem ?

**Steps for Reproduction**
```go
redisStore := redis_store.NewRedis(redis.NewClient(&redis.Options{
	Addr: "127.0.0.1:6379",
}))

cacheManager := cache.New[string](redisStore)

value, err := cacheManager.Get(ctx, "my-key")
if err != nil {
    panic(err)
}

if value != nil {
    //fetch from cache
} else {
    //fetch from db
    err := cacheManager.Set(ctx, "my-key", "fetched result", store.WithExpiration(15*time.Second))
    if err != nil {
        panic(err)
    }
} 
```
**Expected behavior**:
All parallel requests executing one by one (using sync.Map or RWMutex)

**Actual behavior**:
All parallel requests executing parallel

**Platforms**:
go 1.19 (win and linux)

**Versions**:
v4.1.5

**Comment by Eyal-Shalev** [comment]
Saw some library using the singleflight package
https://pkg.go.dev/golang.org/x/sync/singleflight

**Comment by eko** [comment]
Hi,

This is now fixed by: https://github.com/eko/gocache/pull/243

Closing this issue.
