### ISSUE TITLE
Avoid parallel running a load function for the same key

### ISSUE THREAD

**Issue by advoretsky** [eko/gocache#242]
It's worth to implement parallel run of the load function for the same key on cache miss. Without it under load cache may proxy multiple requests to a backend for the same key.

**Comment by eko** [comment]
Thank you for fixing this. I consider this issue can be closed

**Comment by wchargin** [comment]
adding search keywords: LoadableCache, loader called multiple times. (I'm running v4.1.5 and it took me a while to track down this bug; I did an issue search but didn't find this until I `git blame`d the `singleflight` lines in v4.1.6 and saw that they're new.)
