### ISSUE TITLE
Tag Update Request for Changes in PR #231

### ISSUE THREAD

**Issue by liorkesten** [eko/gocache#250]
The changes in [PR #231](https://github.com/eko/gocache/pull/231) made on September 12, 2023, are not accessible because the latest tag was updated on September 10, 2023. The new library version (lib/v4.1.6) is available, but the tag reflecting the changes in PR #231 has not been updated.

**Suggested Solution:**
Please create a new tag to `store/ristretto` that includes the changes from PR #231 to ensure they are accessible in the latest release.

**Steps for Reproduction**

Set up the following "xxxx" value in the config.yaml configuration file.
Launch binary with the following arguments.
Observe the missing updates from PR #231 in the current release.
Expected behavior:
The changes from PR #231 should be included in the latest release tag so they can be accessed and utilized.

**Actual behavior:**
The changes from PR #231 are not accessible because the latest tag predates the PR.

Platforms:

Browser: N/A
Operating System: N/A
Version: N/A
Versions:

Last tag: store/ristretto/v4.1.2 (Sep 10, 2023)
Expected updated tag: Including changes from PR #231 (Sep 12, 2023)

**Comment by eko** [comment]
Hi @liorkesten,

Thank you for your request.

I just created the `store/ristretto/v4.2.2` tag with the latest Ristretto store features in.

Closing this issue for now but feel free to reopen if you have any issue.
