### ISSUE TITLE
Get all keys

### ISSUE THREAD

**Issue by Chessekeks** [eko/gocache#26]
Hi! Is there some simple way to get all keys in store(by pattern or just all keys) and iterate by received items?

**Comment by eko** [comment]
Hi @Chessekeks,

Thanks for your feedback, however, actually, this is not possible as the stores Gocache is compatible with (Bigcache, Ristretto, ...) do not offer the ability to retrieve all the values in the store.

* Ristretto : https://github.com/dgraph-io/ristretto/blob/master/store.go#L39
* Bigcache: https://github.com/allegro/bigcache/blob/master/bigcache.go#L115
* Redis: https://github.com/go-redis/redis/blob/68dd70bb72bb5cd138ebb44f7c58e0b238916ec6/commands.go#L108

They all have a `Get(key)` method but (except `HGetAll()` on Redis client) they don't have such a method implemented.

These stores are made for caching and there could be probably a lot of entries so this is not what we expect here.

Could you please detail what is your use case? Maybe you can achieve your goals in another way?

Thank you

**Comment by Chessekeks** [comment]
I have several caches for different entities on one redis instance. Keys for each cache started with unique prefix.
Sometimes I need to drop all data for certain cache(prefix), so functions to get all data and iterate by them would be very useful.
I found this way to solve the problem - get all keys by redis client command Keys(pattern) and then iterate by them with your library functions.
I hope someday such functionality will appear for all storages
Thank you for your answer
