### ISSUE TITLE
Issue Running BigCache store and ristretto

### ISSUE THREAD

**Issue by avinash92c** [eko/gocache#47]
Hi,
 i discovered your awesome library today and im trying to run the examples on the readme.
i get the below errors when i try to run them
1)
`
bigcacheClient, _ := bigcache.NewBigCache(bigcache.DefaultConfig(5 * time.Minute))
	bigcacheStore := store.NewBigcache(bigcacheClient, nil) 
	cacheManager := cache.New(bigcacheStore)
	err := cacheManager.Set("my-key", "my-value", nil)
	if err != nil {
		panic(err)
	}

	value, err := cacheManager.Get("my-key")
	log.Println(value, err)
`

_im getting an error marked at  err := cacheManager.Set("my-key", "my-value", nil)_

panic: interface conversion: interface {} is string, not []uint8

goroutine 1 [running]:
github.com/eko/gocache/store.(*BigcacheStore).Set(0xc00019c660, 0x773a20, 0xc000032000, 0x773a20, 0x86e010, 0x0, 0xc00000e201, 0xc000032000)
        D:/Dev/GOPATH/pkg/mod/github.com/eko/gocache@v1.0.0/store/bigcache.go:62 +0x19d
github.com/eko/gocache/codec.(*Codec).Set(0xc00019c680, 0x773a20, 0xc000032000, 0x773a20, 0x86e010, 0x0, 0x875001, 0xc000012140)
        D:/Dev/GOPATH/pkg/mod/github.com/eko/gocache@v1.0.0/codec/codec.go:51 +0x70
github.com/eko/gocache/cache.(*Cache).Set(0xc00016bed8, 0x773a20, 0x86e000, 0x773a20, 0x86e010, 0x0, 0x875860, 0xb18120)
        D:/Dev/GOPATH/pkg/mod/github.com/eko/gocache@v1.0.0/cache/cache.go:39 +0xa2
main.main()
        D:/Dev/GOPATH/src/gokit/examples/cache/main.go:17 +0x28e
exit status 2
-------------------------------------------------------------------------------------------------------
Alternatively when im using the example in the benchmark directly on the store, it works
`
client, _ := bigcache.NewBigCache(bigcache.DefaultConfig(5 * time.Minute))
		store := store.NewBigcache(client, nil)

		key := "test"
		value := []byte("value")

		store.Set(key, value, nil)

		val, err := store.Get(key)
		ba := []byte{}
		for _, b := range val.([]uint8) {
			ba = append(ba, byte(b))
		}
		log.Println(string(ba), err)
`
--------------------------------------------------------------------------------------------------------
2)

`
import (
	"log"

	"github.com/dgraph-io/ristretto"
	"github.com/eko/gocache/cache"
	"github.com/eko/gocache/store"
)

func main() {
	ristrettoCache, err := ristretto.NewCache(&ristretto.Config{
		NumCounters: 1000,
		MaxCost:     100,
		BufferItems: 64,
	})
	if err != nil {
		panic(err)
	}
	ristrettoStore := store.NewRistretto(ristrettoCache, nil)

	cacheManager := cache.New(ristrettoStore)
	err = cacheManager.Set("my-key", "my-value", &cache.Options{Cost: 2})
	if err != nil {
		panic(err)
	}

	value, err := cacheManager.Get("my-key")
	log.Println(value, err)

	cacheManager.Delete("my-key")
}
`
err:
.\main.go:23:48: undefined: cache.Options

i noticed options struct is in store package which is imported.

Could you please help

**Comment by yeqown** [comment]
`bigcache.Set(string, []byte)` the example code got some mistake

**Comment by yeqown** [comment]
`cache.Options` is a mistake too, I have create an PR to fix this, you can see then in the new `README.md`.

https://github.com/eko/gocache/pull/49

**Comment by avinash92c** [comment]
shinchan saved me life.

also the get function is a trainwreck.
its returning a byte array which im having to build to generate my result value

```
	bigcacheClient, _ := bigcache.NewBigCache(bigcache.DefaultConfig(5 * time.Minute))
bigcacheStore := store.NewBigcache(bigcacheClient, nil) // No otions provided (as second argument)

cacheManager := cache.New(bigcacheStore)
err := cacheManager.Set("my-key", []byte("my-value"), nil)
if err != nil {
    panic(err)
}

value,err := cacheManager.Get("my-key")
ba := []byte{}
for _, b := range value.([]uint8) {
	ba = append(ba, byte(b))
}
log.Println(string(ba), err)
```

Also i find the examples to be wildly inconsistent.
```
ristrettoCache, err := ristretto.NewCache(&ristretto.Config{
		NumCounters: 1000,
		MaxCost:     100,
		BufferItems: 64,
	})
	if err != nil {
		panic(err)
	}
	ristrettoStore := store.NewRistretto(ristrettoCache, nil)

	cacheManager := cache.New(ristrettoStore)
	err = cacheManager.Set("my-key", "my-value", &store.Options{Cost: 2})
	if err != nil {
		panic(err)
	}

	value, err := cacheManager.Get("my-key")
	log.Println(value, err)
```

the above now gives me the following error
2020/06/24 14:23:45 <nil> Value not found in Ristretto store

**Comment by yeqown** [comment]
For the first, you have two choice:

```go
// method1, type converting
value, _ := cacheManager.Get("my-key")
src := string(value)

// method2, using marshaler to Set and Get
marshalMgr, err = marshaler.New(cacheManager)
marshalMgr.Set("mykey", "myvalue")

value, _ := marshalMgr.Get("mykey")
// now you get value is an interface with string type underlying
```

As for the second, i must to take a look of `ristretto` and try your case ~

**Comment by avinash92c** [comment]
the ristretto cache is fine for me now. adding a few nano seconds delay did the trick.
the big cache method 1 you specific is fundamentally wrong.
the interface returns []uint8 value type. as i demonstrated in my example.
also the setter expects a byte stream, if i want to store numbers or structs i have to convert them to a []byte representation and pass to set and convert back on get. [Code-Link](https://github.com/eko/gocache/blob/9e07a1840b945767be36e194effbb0e899821663/store/bigcache.go#L57)
you have to process it into a byte array and use.
Isn't the whole point of using a library to reduce all the work and let the library do the work for me

```
value,err := cacheManager.Get("my-key")
ba := []byte{}
for _, b := range value.([]uint8) {
	ba = append(ba, byte(b))
}
```

**Comment by yeqown** [comment]
you misunderstand ~, all I want to express is that if you want to pass params to `bigcache.Set`, you should pass `[]byte`, so you can `Get` with `[]byte`. string can be easy to convert to `[]byte`, but if you have a complicated variable or a not easy to convert type, you should think about `Marshaler` to help you finish converting, rather than convert by yourself, this is what you want ~

**Comment by eko** [comment]
Closing this issue as it does not seems to have an issue with the library.

Feel free to reopen if you still have any issue.
