### ISSUE TITLE
Integrate with Hazelcast

### ISSUE THREAD

**Issue by nfrankel** [eko/gocache#6]
Seems like an interesting project. I believe it would gain more traction if you provided integration with [Hazelcast IMDG](https://hazelcast.org/).

**Comment by eko** [comment]
Hi @nfrankel,

Thank you for suggesting this new cache store, I will try to give it a look in the coming days.

**Comment by nfrankel** [comment]
Thanks @eko. Please let me know if you need help!

**Comment by semihbkgr** [comment]
Hazelcast integration has been added 🚀
This issue can be closed.

**Comment by eko** [comment]
Thank you @semihbkgr!
