### ISSUE TITLE
Redis V8

### ISSUE THREAD

**Issue by josefld** [eko/gocache#80]
Hi there! I'm about to upgrade redis lib to V8. 
I wanted to know, before I start, if there is any particular reason of using v7 instead of v8? and why the upgrade isn't done today?

Any considerations I should know?

Thanks in advance.

Jose.-

**Comment by josefld** [comment]
I believe that's only a matter of create a new tag? master branch has v8 already

**Comment by eko** [comment]
Hi,

I just released the tag v1.2.0 with redis/v8 (https://github.com/eko/gocache/releases/tag/v1.2.0)

Closing this issue for now but feel free to reopen if you still have any issue

**Comment by josefld** [comment]
Thanks a lot @eko ! for taking the time to do it!
