### ISSUE TITLE
redis store does not conform to store interface

### ISSUE THREAD

**Issue by on99** [eko/gocache#81]
https://github.com/eko/gocache#redis this is not compilable because `*store.RedisStore` does not implement `store.StoreInterface`

**Comment by majuansari** [comment]
Got the same issue

When I ran go mod vendor the code retrieved has 
`func (s *RedisStore) Set(ctx context.Context, key interface{}, value interface{}, options *Options) error {
`

But in github it seems to be fine

`func (s *RedisStore) Set(key interface{}, value interface{}, options *Options) error {
`

Any idea why it would happen?

**Comment by silenthh** [comment]
go get  github.com/eko/gocache@master

**Comment by majuansari** [comment]
How can I upgrade to v2.0.0?  

I am getting the following error
 
require github.com/eko/gocache: version "2.1.1" invalid: unknown revision 2.1.1

**Comment by FDKevin0** [comment]
@majuansari `go get github.com/eko/gocache/v2`

**Comment by eko** [comment]
Thanks for your reply, indeed this is the way
